name: walden
title: Walden
base: core24
version: '1.0.4'
summary: A minimal, distraction-free, local desktop blog publisher
description: |
  Walden is a minimal, distraction-free, desktop blog 
  publisher that integrates directly with your Github Pages 
  backed sites. Spend less time tinkering in Github and more time 
  writing the next great article or novel.

license: GPL-2.0+
contact: https://github.com/aaronprisk/walden
website: https://aaronprisk.com
issues: https://github.com/aaronprisk/walden/issues
source-code: https://github.com/aaronprisk/walden

icon: snap/gui/walden.png

confinement: strict
grade: stable

lint:
  ignore:
    - library
    - gpu

apps:
  walden:
    command: walden/walden --no-sandbox
    extensions: [gnome]
    plugs:
      - browser-support
      - network
      - network-bind
      - home
      - audio-playback
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  walden:
    plugin: nil
    source: .
    override-build: |
      npm install
      export DEBUG=electron-packager,electron-download
      
      npx --yes electron-packager . --overwrite --platform=linux --out=release-build --prune=true
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/walden
      cp -rv ./release-build/walden-linux-*/* $SNAPCRAFT_PART_INSTALL/walden/
    build-snaps:
      - node/22/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
